{
 "title": "pod status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "All pods stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Completed pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{reason=\"Completed\"})"
    }
   ]
  },
  {
   "title": "Error pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{reason=\"Error\"})"
    }
   ]
  },
  {
   "title": "count restart pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total > 0)"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting > 0)"
    }
   ]
  },
  {
   "title": "OOMKilled pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{reason=\"OOMKilled\"})"
    }
   ]
  },
  { "title": "Extended info of pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "count terminated pods by reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "count waiting pods by reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "count pods by status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  { "title": "restarted pod by  namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "datasource" },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "restarted pods in NS $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}